<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\Templates\EmailTemplate.html" />
	  <Content Remove="wwwroot\Templates\Subs.html" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Admin\Data\" />
		<Folder Include="Areas\User\Data\" />
		<Folder Include="wwwroot\images\avatar\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\elen-master\.DS_Store" />
	  <None Include="wwwroot\elen-master\css\.DS_Store" />
	  <None Include="wwwroot\elen-master\css\bootstrap\.DS_Store" />
	  <None Include="wwwroot\elen-master\css\css\.DS_Store" />
	  <None Include="wwwroot\elen-master\fonts\.DS_Store" />
	  <None Include="wwwroot\elen-master\fonts\flaticon\.DS_Store" />
	  <None Include="wwwroot\elen-master\fonts\ionicons\fonts\.DS_Store" />
	  <None Include="wwwroot\elen-master\images\.DS_Store" />
	  <None Include="wwwroot\elen-master\js\.DS_Store" />
	  <None Include="wwwroot\elen-master\scss\.DS_Store" />
	  <None Include="wwwroot\Templates\EmailTemplate.html" />
	  <None Include="wwwroot\Templates\Subs.html" />
	</ItemGroup>

	<ItemGroup>
		<!-- Humanizer kütüphanesi -->
		<PackageReference Include="AspNetCoreHero.ToastNotification" Version="1.1.0" />
		<PackageReference Include="Humanizer" Version="2.14.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.13" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.3.0" />

		<!-- ASP.NET Core paketleri -->
		<!-- Entity Framework Core paketleri -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- Code Generation ve Diğer Paketler -->
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
		<PackageReference Include="Microsoft.Web.Infrastructure" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
		<!-- Proje Referansları -->
		<ProjectReference Include="..\Business\Business.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Views\Shared\_ViewImports.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>
